/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;
import Classes.*;
import DAO.*;
import javax.swing.*;
import DB.*;


/**
 *
 * @author User
 */
public class TelaAtendente extends javax.swing.JDialog {

    /**
     * Creates new form TelaPaciente
     */
    public TelaAtendente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        
        (new MedicoDAO()).carregaMedico(jComboBoxEscolherMedico);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TELAFUNDO = new javax.swing.JPanel();
        JPanelOpcoesGerenciar = new javax.swing.JPanel();
        jButtonVoltar = new javax.swing.JButton();
        BotaoGerenciarPacientes = new javax.swing.JButton();
        BotaoGerenciarConsultas = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        JPanelOpcoesCustomizar = new javax.swing.JPanel();
        telagerenciarpacientes = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        TelaCadastrarPaciente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NomePaciente = new javax.swing.JTextField();
        CPFPaciente = new javax.swing.JTextField();
        campoDia = new javax.swing.JTextField();
        SexoPaciente = new javax.swing.JTextField();
        TelefonePaciente = new javax.swing.JTextField();
        CEPPaciente = new javax.swing.JTextField();
        EmailPaciente = new javax.swing.JTextField();
        BotaoCadastrarPaciente = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        campoMes = new javax.swing.JTextField();
        campoAno = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        TelaAlterarCadastroPaciente = new javax.swing.JPanel();
        AlterarCEPPaciente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        AlterarEmailPaciente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        BotaoAlterarPaciente = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        AlterarNomePaciente = new javax.swing.JTextField();
        AlterarCPFPaciente = new javax.swing.JTextField();
        campoDiaAlterar = new javax.swing.JTextField();
        AlterarSexoPaciente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        AlterarTelefonePaciente = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        campoMesAlterar = new javax.swing.JTextField();
        campoAnoAlterar = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        TelaExcluirCadastroPaciente = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        CPFExcluir = new javax.swing.JTextField();
        BotaoExcluirPaciente = new javax.swing.JButton();
        telagerenciarconsultas = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        TelaAgendar = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ObservacaoConsulta = new javax.swing.JTextArea();
        campoHoraConsulta = new javax.swing.JTextField();
        campoDiaConsulta = new javax.swing.JTextField();
        CPFConsulta = new javax.swing.JTextField();
        BotaoAgendarConsulta = new javax.swing.JButton();
        campoMesConsulta = new javax.swing.JTextField();
        campoAnoConsulta = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        campoMinutoConsulta = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jComboBoxEscolherMedico = new javax.swing.JComboBox<>();
        TelaCancelarConsulta = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        IDConsultaCancelar = new javax.swing.JTextField();
        BotaoCancelarConsulta = new javax.swing.JButton();
        jButtonBuscarIDConsultaCancelar = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jTextFieldCPFBuscarConsultaCancelar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TELAFUNDO.setBackground(new java.awt.Color(0, 204, 204));
        TELAFUNDO.setPreferredSize(new java.awt.Dimension(750, 500));

        JPanelOpcoesGerenciar.setBackground(new java.awt.Color(204, 255, 255));

        jButtonVoltar.setBackground(new java.awt.Color(255, 204, 204));
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        BotaoGerenciarPacientes.setBackground(new java.awt.Color(0, 255, 255));
        BotaoGerenciarPacientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotaoGerenciarPacientes.setText("Gerenciar Pacientes");
        BotaoGerenciarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGerenciarPacientesActionPerformed(evt);
            }
        });

        BotaoGerenciarConsultas.setBackground(new java.awt.Color(0, 255, 255));
        BotaoGerenciarConsultas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotaoGerenciarConsultas.setText("Gerenciar Consultas");
        BotaoGerenciarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGerenciarConsultasActionPerformed(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/saude.png"))); // NOI18N

        javax.swing.GroupLayout JPanelOpcoesGerenciarLayout = new javax.swing.GroupLayout(JPanelOpcoesGerenciar);
        JPanelOpcoesGerenciar.setLayout(JPanelOpcoesGerenciarLayout);
        JPanelOpcoesGerenciarLayout.setHorizontalGroup(
            JPanelOpcoesGerenciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelOpcoesGerenciarLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(59, 59, 59))
            .addGroup(JPanelOpcoesGerenciarLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(JPanelOpcoesGerenciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotaoGerenciarPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoGerenciarConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(jButtonVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanelOpcoesGerenciarLayout.setVerticalGroup(
            JPanelOpcoesGerenciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelOpcoesGerenciarLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(40, 40, 40)
                .addComponent(BotaoGerenciarPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotaoGerenciarConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jButtonVoltar)
                .addGap(66, 66, 66))
        );

        JPanelOpcoesCustomizar.setBackground(new java.awt.Color(204, 0, 204));

        telagerenciarpacientes.setBackground(new java.awt.Color(0, 204, 204));

        jTabbedPane1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setText("CPF:");

        jLabel2.setText("Data de Nascimento:");

        jLabel3.setText("Nome:");

        jLabel4.setText("Telefone:");

        jLabel5.setText("Sexo:");

        jLabel6.setText("Email:");

        jLabel7.setText("CEP:");

        NomePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomePacienteActionPerformed(evt);
            }
        });

        CPFPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPFPacienteActionPerformed(evt);
            }
        });

        EmailPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailPacienteActionPerformed(evt);
            }
        });

        BotaoCadastrarPaciente.setText("Cadastrar");
        BotaoCadastrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarPacienteActionPerformed(evt);
            }
        });

        jLabel24.setForeground(new java.awt.Color(153, 153, 153));
        jLabel24.setText("Ex: M ou F");

        jLabel25.setText("-");

        jLabel27.setText("-");

        javax.swing.GroupLayout TelaCadastrarPacienteLayout = new javax.swing.GroupLayout(TelaCadastrarPaciente);
        TelaCadastrarPaciente.setLayout(TelaCadastrarPacienteLayout);
        TelaCadastrarPacienteLayout.setHorizontalGroup(
            TelaCadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaCadastrarPacienteLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(TelaCadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TelaCadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaCadastrarPacienteLayout.createSequentialGroup()
                        .addGroup(TelaCadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(TelaCadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(EmailPaciente)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TelaCadastrarPacienteLayout.createSequentialGroup()
                                    .addGroup(TelaCadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(CEPPaciente, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TelefonePaciente, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CPFPaciente, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TelaCadastrarPacienteLayout.createSequentialGroup()
                                            .addComponent(campoDia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel25)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(campoMes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel27)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(campoAno, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addContainerGap(275, Short.MAX_VALUE))
                    .addGroup(TelaCadastrarPacienteLayout.createSequentialGroup()
                        .addGroup(TelaCadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotaoCadastrarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(TelaCadastrarPacienteLayout.createSequentialGroup()
                                .addComponent(SexoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        TelaCadastrarPacienteLayout.setVerticalGroup(
            TelaCadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaCadastrarPacienteLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(TelaCadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TelaCadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CPFPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TelaCadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaCadastrarPacienteLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(TelaCadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SexoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)))
                    .addGroup(TelaCadastrarPacienteLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(TelaCadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TelefonePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(TelaCadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CEPPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(TelaCadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campoAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25)
                        .addComponent(jLabel27)))
                .addGap(17, 17, 17)
                .addGroup(TelaCadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(BotaoCadastrarPaciente)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastrar ", TelaCadastrarPaciente);

        AlterarCEPPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarCEPPacienteActionPerformed(evt);
            }
        });

        jLabel8.setText("Nome:");

        AlterarEmailPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarEmailPacienteActionPerformed(evt);
            }
        });

        jLabel9.setText("Telefone:");

        BotaoAlterarPaciente.setText("Alterar");
        BotaoAlterarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAlterarPacienteActionPerformed(evt);
            }
        });

        jLabel10.setText("Sexo:");

        jLabel11.setText("Email:");

        jLabel12.setText("CEP:");

        AlterarNomePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarNomePacienteActionPerformed(evt);
            }
        });

        AlterarCPFPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarCPFPacienteActionPerformed(evt);
            }
        });

        jLabel13.setText("Informe o CPF do paciente que deseja alterar:");

        AlterarTelefonePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarTelefonePacienteActionPerformed(evt);
            }
        });

        jLabel14.setText("Data de Nascimento:");

        jLabel16.setText("Dados a serem alterados:");

        jLabel26.setForeground(new java.awt.Color(153, 153, 153));
        jLabel26.setText("Ex: M ou F");

        campoAnoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAnoAlterarActionPerformed(evt);
            }
        });

        jLabel29.setText("-");

        jLabel30.setText("-");

        javax.swing.GroupLayout TelaAlterarCadastroPacienteLayout = new javax.swing.GroupLayout(TelaAlterarCadastroPaciente);
        TelaAlterarCadastroPaciente.setLayout(TelaAlterarCadastroPacienteLayout);
        TelaAlterarCadastroPacienteLayout.setHorizontalGroup(
            TelaAlterarCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaAlterarCadastroPacienteLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(TelaAlterarCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaAlterarCadastroPacienteLayout.createSequentialGroup()
                        .addGroup(TelaAlterarCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(TelaAlterarCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TelaAlterarCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(AlterarCPFPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AlterarNomePaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                .addComponent(AlterarEmailPaciente)
                                .addComponent(AlterarCEPPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BotaoAlterarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(TelaAlterarCadastroPacienteLayout.createSequentialGroup()
                                    .addGroup(TelaAlterarCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(AlterarSexoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(TelaAlterarCadastroPacienteLayout.createSequentialGroup()
                                            .addComponent(campoDiaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel29)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(campoMesAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel30)))
                                    .addGroup(TelaAlterarCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(TelaAlterarCadastroPacienteLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                            .addComponent(jLabel26)
                                            .addGap(16, 16, 16))
                                        .addGroup(TelaAlterarCadastroPacienteLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(campoAnoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE)))))
                            .addComponent(AlterarTelefonePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(286, Short.MAX_VALUE))
                    .addGroup(TelaAlterarCadastroPacienteLayout.createSequentialGroup()
                        .addGroup(TelaAlterarCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        TelaAlterarCadastroPacienteLayout.setVerticalGroup(
            TelaAlterarCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaAlterarCadastroPacienteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(TelaAlterarCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AlterarCPFPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TelaAlterarCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AlterarNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TelaAlterarCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDiaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoMesAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoAnoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TelaAlterarCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AlterarSexoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(31, 31, 31)
                .addGroup(TelaAlterarCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AlterarTelefonePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TelaAlterarCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AlterarCEPPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TelaAlterarCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AlterarEmailPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(BotaoAlterarPaciente)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Alterar", TelaAlterarCadastroPaciente);

        jLabel15.setText("Informe o CPF do paciente que deseja excluir:");

        BotaoExcluirPaciente.setText("Excluir");
        BotaoExcluirPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExcluirPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TelaExcluirCadastroPacienteLayout = new javax.swing.GroupLayout(TelaExcluirCadastroPaciente);
        TelaExcluirCadastroPaciente.setLayout(TelaExcluirCadastroPacienteLayout);
        TelaExcluirCadastroPacienteLayout.setHorizontalGroup(
            TelaExcluirCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaExcluirCadastroPacienteLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TelaExcluirCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotaoExcluirPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CPFExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(316, Short.MAX_VALUE))
        );
        TelaExcluirCadastroPacienteLayout.setVerticalGroup(
            TelaExcluirCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaExcluirCadastroPacienteLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(TelaExcluirCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CPFExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BotaoExcluirPaciente)
                .addContainerGap(348, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Excluir", TelaExcluirCadastroPaciente);

        javax.swing.GroupLayout telagerenciarpacientesLayout = new javax.swing.GroupLayout(telagerenciarpacientes);
        telagerenciarpacientes.setLayout(telagerenciarpacientesLayout);
        telagerenciarpacientesLayout.setHorizontalGroup(
            telagerenciarpacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telagerenciarpacientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        telagerenciarpacientesLayout.setVerticalGroup(
            telagerenciarpacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        telagerenciarconsultas.setBackground(new java.awt.Color(0, 204, 204));

        jTabbedPane2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel17.setText("Data da Consulta:");

        jLabel18.setText("Observação:");

        jLabel19.setText("CPF do paciente:");

        jLabel20.setText("Médico(a):");

        jLabel21.setText("Hora da Consulta:");

        ObservacaoConsulta.setColumns(20);
        ObservacaoConsulta.setRows(5);
        jScrollPane1.setViewportView(ObservacaoConsulta);

        CPFConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPFConsultaActionPerformed(evt);
            }
        });

        BotaoAgendarConsulta.setText("Agendar");
        BotaoAgendarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAgendarConsultaActionPerformed(evt);
            }
        });

        jLabel31.setText("-");

        jLabel32.setText("-");

        jLabel33.setText(":");

        jComboBoxEscolherMedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxEscolherMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEscolherMedicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TelaAgendarLayout = new javax.swing.GroupLayout(TelaAgendar);
        TelaAgendar.setLayout(TelaAgendarLayout);
        TelaAgendarLayout.setHorizontalGroup(
            TelaAgendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaAgendarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(TelaAgendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaAgendarLayout.createSequentialGroup()
                        .addComponent(jComboBoxEscolherMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(TelaAgendarLayout.createSequentialGroup()
                        .addGroup(TelaAgendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TelaAgendarLayout.createSequentialGroup()
                                .addGroup(TelaAgendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(TelaAgendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(TelaAgendarLayout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(campoDiaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaAgendarLayout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(campoHoraConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(TelaAgendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(TelaAgendarLayout.createSequentialGroup()
                                        .addComponent(jLabel31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoMesConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoAnoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(TelaAgendarLayout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoMinutoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(TelaAgendarLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(TelaAgendarLayout.createSequentialGroup()
                                .addGroup(TelaAgendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20))
                                .addGap(46, 46, 46)
                                .addGroup(TelaAgendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CPFConsulta)
                                    .addComponent(BotaoAgendarConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                        .addContainerGap(287, Short.MAX_VALUE))))
        );
        TelaAgendarLayout.setVerticalGroup(
            TelaAgendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaAgendarLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(TelaAgendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDiaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoMesConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoAnoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TelaAgendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoHoraConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoMinutoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGap(15, 15, 15)
                .addGroup(TelaAgendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TelaAgendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CPFConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxEscolherMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(BotaoAgendarConsulta)
                .addGap(54, 54, 54))
        );

        jTabbedPane2.addTab("Agendar", TelaAgendar);

        jLabel22.setText("Informe o ID da consulta que deseja cancelar:");

        IDConsultaCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDConsultaCancelarActionPerformed(evt);
            }
        });

        BotaoCancelarConsulta.setText("Cancelar");
        BotaoCancelarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelarConsultaActionPerformed(evt);
            }
        });

        jButtonBuscarIDConsultaCancelar.setText("Buscar Consultas");
        jButtonBuscarIDConsultaCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarIDConsultaCancelarActionPerformed(evt);
            }
        });

        jLabel34.setText("CPF do paciente para busca:");

        javax.swing.GroupLayout TelaCancelarConsultaLayout = new javax.swing.GroupLayout(TelaCancelarConsulta);
        TelaCancelarConsulta.setLayout(TelaCancelarConsultaLayout);
        TelaCancelarConsultaLayout.setHorizontalGroup(
            TelaCancelarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaCancelarConsultaLayout.createSequentialGroup()
                .addGroup(TelaCancelarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaCancelarConsultaLayout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(BotaoCancelarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TelaCancelarConsultaLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(TelaCancelarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(TelaCancelarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonBuscarIDConsultaCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IDConsultaCancelar)
                            .addComponent(jTextFieldCPFBuscarConsultaCancelar))))
                .addGap(34, 34, 34))
        );
        TelaCancelarConsultaLayout.setVerticalGroup(
            TelaCancelarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaCancelarConsultaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(TelaCancelarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jTextFieldCPFBuscarConsultaCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscarIDConsultaCancelar)
                .addGap(39, 39, 39)
                .addGroup(TelaCancelarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDConsultaCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotaoCancelarConsulta)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Cancelar", TelaCancelarConsulta);

        javax.swing.GroupLayout telagerenciarconsultasLayout = new javax.swing.GroupLayout(telagerenciarconsultas);
        telagerenciarconsultas.setLayout(telagerenciarconsultasLayout);
        telagerenciarconsultasLayout.setHorizontalGroup(
            telagerenciarconsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telagerenciarconsultasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        telagerenciarconsultasLayout.setVerticalGroup(
            telagerenciarconsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telagerenciarconsultasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout JPanelOpcoesCustomizarLayout = new javax.swing.GroupLayout(JPanelOpcoesCustomizar);
        JPanelOpcoesCustomizar.setLayout(JPanelOpcoesCustomizarLayout);
        JPanelOpcoesCustomizarLayout.setHorizontalGroup(
            JPanelOpcoesCustomizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telagerenciarpacientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPanelOpcoesCustomizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(telagerenciarconsultas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanelOpcoesCustomizarLayout.setVerticalGroup(
            JPanelOpcoesCustomizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telagerenciarpacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPanelOpcoesCustomizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(telagerenciarconsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TELAFUNDOLayout = new javax.swing.GroupLayout(TELAFUNDO);
        TELAFUNDO.setLayout(TELAFUNDOLayout);
        TELAFUNDOLayout.setHorizontalGroup(
            TELAFUNDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TELAFUNDOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanelOpcoesGerenciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanelOpcoesCustomizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        TELAFUNDOLayout.setVerticalGroup(
            TELAFUNDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TELAFUNDOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TELAFUNDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JPanelOpcoesCustomizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPanelOpcoesGerenciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TELAFUNDO, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TELAFUNDO, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        TelaPrincipal telaprincipal = new TelaPrincipal();
        telaprincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void BotaoGerenciarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGerenciarConsultasActionPerformed
        telagerenciarpacientes.setVisible(false);
        telagerenciarconsultas.setVisible(true);
    }//GEN-LAST:event_BotaoGerenciarConsultasActionPerformed

    private void BotaoGerenciarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGerenciarPacientesActionPerformed
        telagerenciarconsultas.setVisible(false);
        telagerenciarpacientes.setVisible(true);
    }//GEN-LAST:event_BotaoGerenciarPacientesActionPerformed

    private void BotaoExcluirPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExcluirPacienteActionPerformed
        // TODO add your handling code here:
         String cpf = CPFExcluir.getText();  
    
    
    if (cpf.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, insira o CPF do paciente para exclusão.", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    
    PacienteDAO pacienteDAO = new PacienteDAO();  
    pacienteDAO.excluirPaciente(cpf); 

    
    //JOptionPane.showMessageDialog(this, "Paciente com CPF " + cpf + " excluído com sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    
    
    CPFExcluir.setText("");
    }//GEN-LAST:event_BotaoExcluirPacienteActionPerformed

    private void AlterarTelefonePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarTelefonePacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlterarTelefonePacienteActionPerformed

    private void AlterarCPFPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarCPFPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlterarCPFPacienteActionPerformed

    private void AlterarNomePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarNomePacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlterarNomePacienteActionPerformed

    private void AlterarEmailPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarEmailPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlterarEmailPacienteActionPerformed

    private void AlterarCEPPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarCEPPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlterarCEPPacienteActionPerformed

    private void EmailPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailPacienteActionPerformed

    private void CPFPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPFPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPFPacienteActionPerformed

    private void BotaoCancelarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelarConsultaActionPerformed
      
         String idConsultaStr = IDConsultaCancelar.getText();

    // Validar se o campo está preenchido
    if (idConsultaStr.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, insira o ID da consulta a ser cancelada!", "Atenção", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Converter o ID para inteiro
    int idConsulta;
    try {
        idConsulta = Integer.parseInt(idConsultaStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "O ID da consulta deve ser um número válido!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    ConsultaDAO consultaDAO =  new ConsultaDAO();

   
    consultaDAO.cancelarConsulta(idConsulta);

    // Limpar o campo de entrada
    IDConsultaCancelar.setText("");

    }//GEN-LAST:event_BotaoCancelarConsultaActionPerformed

    private void IDConsultaCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDConsultaCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDConsultaCancelarActionPerformed

    private void CPFConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPFConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPFConsultaActionPerformed

    private void BotaoCadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarPacienteActionPerformed
        // TODO add your handling code here:
    String nome = NomePaciente.getText();
    String cpf = CPFPaciente.getText();
    String sexo = SexoPaciente.getText();
    String telefone = TelefonePaciente.getText();
    String cep = CEPPaciente.getText();
    String email = EmailPaciente.getText();
    String dia = campoDia.getText();  
    String mes = campoMes.getText();  
    String ano = campoAno.getText();
    
    
    if (dia.isEmpty() || mes.isEmpty() || ano.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, preencha o dia, mês e ano da data de nascimento.", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Concatena para formar a data no formato 'YYYY-MM-DD'
    String dataNascimento = ano + "-" + mes + "-" + dia;

    
    Paciente paciente = new Paciente(cpf, nome, telefone, dataNascimento, email, sexo, cep);
    PacienteDAO pacienteDAO = new PacienteDAO();

    // Chama o método para salvar o paciente no banco de dados
    pacienteDAO.salvarPaciente(paciente);
    
    // Exibe uma mensagem de sucesso ou erro
    JOptionPane.showMessageDialog(this, "Paciente cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    
    // Limpa os campos após o cadastro (opcional)
    NomePaciente.setText("");
    CPFPaciente.setText("");
    campoDia.setText("");
    campoMes.setText("");
    campoAno.setText("");
    SexoPaciente.setText("");
    TelefonePaciente.setText("");
    CEPPaciente.setText("");
    EmailPaciente.setText("");
        
    }//GEN-LAST:event_BotaoCadastrarPacienteActionPerformed

    private void NomePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomePacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomePacienteActionPerformed

    private void campoAnoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAnoAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoAnoAlterarActionPerformed

    private void BotaoAlterarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAlterarPacienteActionPerformed
        // TODO add your handling code here:
    String nome = AlterarNomePaciente.getText();
    String cpf = AlterarCPFPaciente.getText();
    String telefone = AlterarTelefonePaciente.getText();
    String sexo = AlterarSexoPaciente.getText();
    String cep = AlterarCEPPaciente.getText();
    String email = AlterarEmailPaciente.getText();

    
    String dia = campoDiaAlterar.getText();  
    String mes = campoMesAlterar.getText();  
    String ano = campoAnoAlterar.getText();  

   
    String dataNascimento = ano + "-" + mes + "-" + dia;

   
    Paciente paciente = new Paciente(cpf, nome, telefone, dataNascimento, email, sexo, cep);

    
    PacienteDAO pacienteDAO = new PacienteDAO(); 
    pacienteDAO.alterarPaciente(paciente);

    

    
    AlterarNomePaciente.setText("");
    AlterarCPFPaciente.setText("");
    AlterarTelefonePaciente.setText("");
    AlterarCEPPaciente.setText("");
    AlterarEmailPaciente.setText("");
    campoDiaAlterar.setText("");
    campoMesAlterar.setText("");
    campoAnoAlterar.setText("");

    }//GEN-LAST:event_BotaoAlterarPacienteActionPerformed

    private void BotaoAgendarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAgendarConsultaActionPerformed
        // TODO add your handling code here:
    String dataConsulta = campoAnoConsulta.getText()+ "-" + campoMesConsulta.getText() + "-" + campoDiaConsulta.getText();
    String horaConsulta = campoHoraConsulta.getText() + ":" + campoMinutoConsulta.getText();
    String observacao = ObservacaoConsulta.getText();
    String cpf_paciente = CPFConsulta.getText();
    String crm_medico = ((Medico)jComboBoxEscolherMedico.getSelectedItem()).getCrm();

    
    if (cpf_paciente.isEmpty() || crm_medico.isEmpty() || dataConsulta.isEmpty() || horaConsulta.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos obrigatórios!", "Atenção", JOptionPane.WARNING_MESSAGE);
        return;
    }
    Consulta consulta = new Consulta( dataConsulta,  horaConsulta,  observacao,  cpf_paciente,  crm_medico);
    ConsultaDAO consultaDAO= new ConsultaDAO();


    
    consultaDAO.salvarConsulta(consulta);


        
    }//GEN-LAST:event_BotaoAgendarConsultaActionPerformed

    private void jButtonBuscarIDConsultaCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarIDConsultaCancelarActionPerformed

    String cpfPaciente = jTextFieldCPFBuscarConsultaCancelar.getText();

    // Valida se o campo não está vazio
    if (cpfPaciente.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, insira o CPF do paciente!", "Atenção", JOptionPane.WARNING_MESSAGE);
        return;
    }

    ConsultaDAO consultaDAO = new ConsultaDAO();
    consultaDAO.buscarConsultasPorPaciente(cpfPaciente);

    // Limpa o campo de texto após a busca
    jTextFieldCPFBuscarConsultaCancelar.setText("");


    }//GEN-LAST:event_jButtonBuscarIDConsultaCancelarActionPerformed

    private void jComboBoxEscolherMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEscolherMedicoActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jComboBoxEscolherMedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaAtendente dialog = new TelaAtendente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlterarCEPPaciente;
    private javax.swing.JTextField AlterarCPFPaciente;
    private javax.swing.JTextField AlterarEmailPaciente;
    private javax.swing.JTextField AlterarNomePaciente;
    private javax.swing.JTextField AlterarSexoPaciente;
    private javax.swing.JTextField AlterarTelefonePaciente;
    private javax.swing.JButton BotaoAgendarConsulta;
    private javax.swing.JButton BotaoAlterarPaciente;
    private javax.swing.JButton BotaoCadastrarPaciente;
    private javax.swing.JButton BotaoCancelarConsulta;
    private javax.swing.JButton BotaoExcluirPaciente;
    private javax.swing.JButton BotaoGerenciarConsultas;
    private javax.swing.JButton BotaoGerenciarPacientes;
    private javax.swing.JTextField CEPPaciente;
    private javax.swing.JTextField CPFConsulta;
    private javax.swing.JTextField CPFExcluir;
    private javax.swing.JTextField CPFPaciente;
    private javax.swing.JTextField EmailPaciente;
    private javax.swing.JTextField IDConsultaCancelar;
    private javax.swing.JPanel JPanelOpcoesCustomizar;
    private javax.swing.JPanel JPanelOpcoesGerenciar;
    private javax.swing.JTextField NomePaciente;
    private javax.swing.JTextArea ObservacaoConsulta;
    private javax.swing.JTextField SexoPaciente;
    private javax.swing.JPanel TELAFUNDO;
    private javax.swing.JPanel TelaAgendar;
    private javax.swing.JPanel TelaAlterarCadastroPaciente;
    private javax.swing.JPanel TelaCadastrarPaciente;
    private javax.swing.JPanel TelaCancelarConsulta;
    private javax.swing.JPanel TelaExcluirCadastroPaciente;
    private javax.swing.JTextField TelefonePaciente;
    private javax.swing.JTextField campoAno;
    private javax.swing.JTextField campoAnoAlterar;
    private javax.swing.JTextField campoAnoConsulta;
    private javax.swing.JTextField campoDia;
    private javax.swing.JTextField campoDiaAlterar;
    private javax.swing.JTextField campoDiaConsulta;
    private javax.swing.JTextField campoHoraConsulta;
    private javax.swing.JTextField campoMes;
    private javax.swing.JTextField campoMesAlterar;
    private javax.swing.JTextField campoMesConsulta;
    private javax.swing.JTextField campoMinutoConsulta;
    private javax.swing.JButton jButtonBuscarIDConsultaCancelar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxEscolherMedico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextFieldCPFBuscarConsultaCancelar;
    private javax.swing.JPanel telagerenciarconsultas;
    private javax.swing.JPanel telagerenciarpacientes;
    // End of variables declaration//GEN-END:variables
}
