/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.*;
import DAO.*;
import Classes.*;

/**
 *
 * @author User
 */
public class TelaMedica extends javax.swing.JDialog {

    /**
     * Creates new form TelaPaciente
     */
    public TelaMedica(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        (new MedicoDAO()).carregaMedico(jComboBoxRelatorioMedicoConsulta);
        (new MedicoDAO()).carregaMedico(jComboBoxRelatorioMedicoExame);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TELAFUNDO = new javax.swing.JPanel();
        JPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        botaogerenciarexames = new javax.swing.JButton();
        botaorelatorios = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        botaogerenciarexames1 = new javax.swing.JButton();
        FUNDOTELAS = new javax.swing.JPanel();
        telagerenciarmedicos = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        especialidadeMedico = new javax.swing.JTextArea();
        emailMedicoCadastrar = new javax.swing.JTextField();
        TelefoneMedicoCadastrar = new javax.swing.JTextField();
        ButtonCadastrarMedico = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jTextFieldCRMCadastrar = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldNomeMedicoCadastrar = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        CRMExcluir = new javax.swing.JTextField();
        excluirMedico = new javax.swing.JButton();
        telagerenciarexames = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DescricaoExame = new javax.swing.JTextArea();
        campoHoraExame = new javax.swing.JTextField();
        campoDiaExame = new javax.swing.JTextField();
        marcarExame = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jTextFieldCPFExame = new javax.swing.JTextField();
        jButtonBuscarConsultaParaExame = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIDConsultaExame = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        campoMesExame = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        campoAnoExame = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        campoMinutoExame = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        IdExameCancelar = new javax.swing.JTextField();
        cancelarExame = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCPFCancelarExame = new javax.swing.JTextField();
        jButtonBuscarExame = new javax.swing.JButton();
        telarelatorios = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButtonBuscarPorPacienteC = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCPFRelatoriosC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButtonBuscarPorMedicoC = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldRelatorioCampoDiaConsulta = new javax.swing.JTextField();
        jButtonBuscarPorDiaC = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextFieldRelatorioCampoMesConsulta = new javax.swing.JTextField();
        jTextFieldRelatorioCampoAnoConsulta = new javax.swing.JTextField();
        jComboBoxRelatorioMedicoConsulta = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldCPFRelatoriosE = new javax.swing.JTextField();
        jButtonBuscarPorPacienteE = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButtonBuscarPorMedicoE = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldRelatorioCampoDiaExame = new javax.swing.JTextField();
        jButtonBuscarPorDiaE = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jTextFieldRelatorioCampoMesExame = new javax.swing.JTextField();
        jTextFieldRelatorioCampoAnoExame = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jComboBoxRelatorioMedicoExame = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TELAFUNDO.setBackground(new java.awt.Color(0, 204, 204));
        TELAFUNDO.setPreferredSize(new java.awt.Dimension(750, 500));

        JPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        botaogerenciarexames.setBackground(new java.awt.Color(0, 255, 255));
        botaogerenciarexames.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaogerenciarexames.setText("Gerenciar Exames");
        botaogerenciarexames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaogerenciarexamesActionPerformed(evt);
            }
        });

        botaorelatorios.setBackground(new java.awt.Color(0, 255, 255));
        botaorelatorios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaorelatorios.setText("Relatórios");
        botaorelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaorelatoriosActionPerformed(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/saude.png"))); // NOI18N

        botaogerenciarexames1.setBackground(new java.awt.Color(0, 255, 255));
        botaogerenciarexames1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaogerenciarexames1.setText("Gerenciar Médicos");
        botaogerenciarexames1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaogerenciarexames1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanel1Layout = new javax.swing.GroupLayout(JPanel1);
        JPanel1.setLayout(JPanel1Layout);
        JPanel1Layout.setHorizontalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel1Layout.createSequentialGroup()
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaorelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaogerenciarexames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaogerenciarexames1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(57, 57, 57))))
        );
        JPanel1Layout.setVerticalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaogerenciarexames1)
                .addGap(18, 18, 18)
                .addComponent(botaogerenciarexames)
                .addGap(18, 18, 18)
                .addComponent(botaorelatorios)
                .addGap(52, 52, 52)
                .addComponent(jButton1)
                .addGap(66, 66, 66))
        );

        telagerenciarmedicos.setBackground(new java.awt.Color(0, 204, 204));

        jLabel19.setText("Especialidade:");

        jLabel20.setText("Email:");

        jLabel21.setText("Telefone:");

        especialidadeMedico.setColumns(20);
        especialidadeMedico.setRows(5);
        jScrollPane2.setViewportView(especialidadeMedico);

        emailMedicoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailMedicoCadastrarActionPerformed(evt);
            }
        });

        ButtonCadastrarMedico.setText("Cadastrar");
        ButtonCadastrarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadastrarMedicoActionPerformed(evt);
            }
        });

        jLabel30.setText("CRM:");

        jTextFieldCRMCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCRMCadastrarActionPerformed(evt);
            }
        });

        jLabel22.setText("Nome:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCRMCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldNomeMedicoCadastrar))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel19)
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addComponent(ButtonCadastrarMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                                        .addComponent(TelefoneMedicoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(emailMedicoCadastrar)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCRMCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextFieldNomeMedicoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelefoneMedicoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailMedicoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(ButtonCadastrarMedico)
                .addGap(36, 36, 36))
        );

        jTabbedPane3.addTab("Cadastrar Médico", jPanel5);

        jLabel24.setText("Informe o CRM do médico que deseja cancelar:");

        excluirMedico.setText("Excluir");
        excluirMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirMedicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CRMExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(excluirMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CRMExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(excluirMedico)
                .addContainerGap(357, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Excluir Médico", jPanel6);

        javax.swing.GroupLayout telagerenciarmedicosLayout = new javax.swing.GroupLayout(telagerenciarmedicos);
        telagerenciarmedicos.setLayout(telagerenciarmedicosLayout);
        telagerenciarmedicosLayout.setHorizontalGroup(
            telagerenciarmedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telagerenciarmedicosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );
        telagerenciarmedicosLayout.setVerticalGroup(
            telagerenciarmedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telagerenciarmedicosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );

        telagerenciarexames.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setText("Descrição:");

        jLabel2.setText("Hora do Exame:");

        jLabel3.setText("Data do Exame:");

        DescricaoExame.setColumns(20);
        DescricaoExame.setRows(5);
        jScrollPane1.setViewportView(DescricaoExame);

        campoHoraExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoHoraExameActionPerformed(evt);
            }
        });

        marcarExame.setText("Marcar");
        marcarExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcarExameActionPerformed(evt);
            }
        });

        jLabel29.setText("CPF do paciente:");

        jButtonBuscarConsultaParaExame.setText("Buscar Consulta");
        jButtonBuscarConsultaParaExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarConsultaParaExameActionPerformed(evt);
            }
        });

        jLabel5.setText("ID da Consulta:");

        jLabel28.setText("-");

        jLabel31.setText("-");

        jLabel32.setText(":");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCPFExame, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIDConsultaExame, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(marcarExame, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(campoHoraExame, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(campoDiaExame, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(campoMesExame, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(campoMinutoExame, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoAnoExame, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonBuscarConsultaParaExame)
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jTextFieldCPFExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jButtonBuscarConsultaParaExame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldIDConsultaExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDiaExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(campoMesExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(campoAnoExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoHoraExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(campoMinutoExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(marcarExame)
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("Agendar Exame", jPanel2);

        jLabel4.setText("Informe o Id do exame que deseja cancelar:");

        cancelarExame.setText("Cancelar");
        cancelarExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarExameActionPerformed(evt);
            }
        });

        jLabel6.setText("CPF do paciente:");

        jButtonBuscarExame.setText("Buscar Exame");
        jButtonBuscarExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarExameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(29, 29, 29)
                        .addComponent(jTextFieldCPFCancelarExame))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBuscarExame)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cancelarExame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(IdExameCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldCPFCancelarExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jButtonBuscarExame)
                .addGap(67, 67, 67)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdExameCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cancelarExame)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cancelar Exame", jPanel3);

        javax.swing.GroupLayout telagerenciarexamesLayout = new javax.swing.GroupLayout(telagerenciarexames);
        telagerenciarexames.setLayout(telagerenciarexamesLayout);
        telagerenciarexamesLayout.setHorizontalGroup(
            telagerenciarexamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telagerenciarexamesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        telagerenciarexamesLayout.setVerticalGroup(
            telagerenciarexamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telagerenciarexamesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        telarelatorios.setBackground(new java.awt.Color(0, 204, 204));

        jButtonBuscarPorPacienteC.setText("Buscar");
        jButtonBuscarPorPacienteC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarPorPacienteCActionPerformed(evt);
            }
        });

        jLabel7.setText("Consultas por Paciente");

        jLabel8.setText("CPF:");

        jLabel9.setText("Consultas por Médico(a)");

        jLabel10.setText("CRM:");

        jButtonBuscarPorMedicoC.setText("Buscar");
        jButtonBuscarPorMedicoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarPorMedicoCActionPerformed(evt);
            }
        });

        jLabel11.setText("Consultas Por Dia");

        jLabel12.setText("Data:");

        jButtonBuscarPorDiaC.setText("Buscar");
        jButtonBuscarPorDiaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarPorDiaCActionPerformed(evt);
            }
        });

        jLabel25.setText("-");

        jLabel33.setText("-");

        jComboBoxRelatorioMedicoConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBuscarPorPacienteC)
                            .addComponent(jTextFieldCPFRelatoriosC, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBuscarPorMedicoC)
                            .addComponent(jComboBoxRelatorioMedicoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBuscarPorDiaC)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldRelatorioCampoDiaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldRelatorioCampoMesConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldRelatorioCampoAnoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 202, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldCPFRelatoriosC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscarPorPacienteC)
                .addGap(31, 31, 31)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBoxRelatorioMedicoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscarPorMedicoC)
                .addGap(43, 43, 43)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldRelatorioCampoDiaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel33)
                    .addComponent(jTextFieldRelatorioCampoMesConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRelatorioCampoAnoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscarPorDiaC)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Consulta", jPanel1);

        jLabel13.setText("Exames por Paciente");

        jLabel14.setText("CPF:");

        jButtonBuscarPorPacienteE.setText("Buscar");
        jButtonBuscarPorPacienteE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarPorPacienteEActionPerformed(evt);
            }
        });

        jLabel15.setText("Exames por Médico(a)");

        jLabel16.setText("CRM:");

        jButtonBuscarPorMedicoE.setText("Buscar");
        jButtonBuscarPorMedicoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarPorMedicoEActionPerformed(evt);
            }
        });

        jLabel17.setText("Exames Por Dia");

        jLabel18.setText("Data:");

        jButtonBuscarPorDiaE.setText("Buscar");
        jButtonBuscarPorDiaE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarPorDiaEActionPerformed(evt);
            }
        });

        jLabel26.setText("-");

        jLabel27.setText("-");

        jComboBoxRelatorioMedicoExame.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBuscarPorMedicoE)
                            .addComponent(jComboBoxRelatorioMedicoExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBuscarPorPacienteE)
                            .addComponent(jTextFieldCPFRelatoriosE, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBuscarPorDiaE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextFieldRelatorioCampoDiaExame, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldRelatorioCampoMesExame, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldRelatorioCampoAnoExame, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 201, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldCPFRelatoriosE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBuscarPorPacienteE)
                .addGap(37, 37, 37)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jComboBoxRelatorioMedicoExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscarPorMedicoE)
                .addGap(43, 43, 43)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldRelatorioCampoDiaExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jTextFieldRelatorioCampoMesExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRelatorioCampoAnoExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscarPorDiaE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Exames", jPanel4);

        javax.swing.GroupLayout telarelatoriosLayout = new javax.swing.GroupLayout(telarelatorios);
        telarelatorios.setLayout(telarelatoriosLayout);
        telarelatoriosLayout.setHorizontalGroup(
            telarelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telarelatoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        telarelatoriosLayout.setVerticalGroup(
            telarelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telarelatoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout FUNDOTELASLayout = new javax.swing.GroupLayout(FUNDOTELAS);
        FUNDOTELAS.setLayout(FUNDOTELASLayout);
        FUNDOTELASLayout.setHorizontalGroup(
            FUNDOTELASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telagerenciarexames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FUNDOTELASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(telarelatorios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(FUNDOTELASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(telagerenciarmedicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FUNDOTELASLayout.setVerticalGroup(
            FUNDOTELASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telagerenciarexames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FUNDOTELASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(telarelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(FUNDOTELASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(telagerenciarmedicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TELAFUNDOLayout = new javax.swing.GroupLayout(TELAFUNDO);
        TELAFUNDO.setLayout(TELAFUNDOLayout);
        TELAFUNDOLayout.setHorizontalGroup(
            TELAFUNDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TELAFUNDOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FUNDOTELAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        TELAFUNDOLayout.setVerticalGroup(
            TELAFUNDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TELAFUNDOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TELAFUNDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FUNDOTELAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TELAFUNDO, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TELAFUNDO, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaPrincipal telaprincipal = new TelaPrincipal();
        telaprincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botaogerenciarexamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaogerenciarexamesActionPerformed
        telagerenciarmedicos.setVisible(false);
        telarelatorios.setVisible(false);
        telagerenciarexames.setVisible(true);
    }//GEN-LAST:event_botaogerenciarexamesActionPerformed

    private void botaorelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaorelatoriosActionPerformed
        telagerenciarmedicos.setVisible(false);
        telagerenciarexames.setVisible(false);
        telarelatorios.setVisible(true);
    }//GEN-LAST:event_botaorelatoriosActionPerformed

    private void campoHoraExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoHoraExameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoHoraExameActionPerformed

    private void botaogerenciarexames1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaogerenciarexames1ActionPerformed
        telarelatorios.setVisible(false);
        telagerenciarexames.setVisible(false);
        telagerenciarmedicos.setVisible(true);
    }//GEN-LAST:event_botaogerenciarexames1ActionPerformed

    private void emailMedicoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailMedicoCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailMedicoCadastrarActionPerformed

    private void ButtonCadastrarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadastrarMedicoActionPerformed
        // TODO add your handling code here:
        
    String crm = jTextFieldCRMCadastrar.getText();
    String nome = jTextFieldNomeMedicoCadastrar.getText();
    String especialidade = especialidadeMedico.getText();
    String telefone = TelefoneMedicoCadastrar.getText();
    String email = emailMedicoCadastrar.getText();

    // Validações básicas
    if (crm.isEmpty() || nome.isEmpty() || especialidade.isEmpty() || telefone.isEmpty() || email.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos!", "Atenção", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Cria um objeto Medico
    Medico medico = new Medico(crm, nome, especialidade, telefone, email);

    // Salva o médico no banco de dados
    MedicoDAO medicoDAO = new MedicoDAO();
    medicoDAO.salvarMedico(medico);

    // Limpa os campos após salvar
    jTextFieldCRMCadastrar.setText("");
    jTextFieldNomeMedicoCadastrar.setText("");
    especialidadeMedico.setText("");
    TelefoneMedicoCadastrar.setText("");
    emailMedicoCadastrar.setText("");
        
    }//GEN-LAST:event_ButtonCadastrarMedicoActionPerformed

    private void jTextFieldCRMCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCRMCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCRMCadastrarActionPerformed

    private void excluirMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirMedicoActionPerformed
         String crm = CRMExcluir.getText();

    // Valida se o campo CRM está preenchido
    if (crm.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, insira o CRM do médico que deseja excluir!", "Atenção", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Chama a função para excluir o médico
    MedicoDAO medicoDAO = new MedicoDAO();
    medicoDAO.excluirMedico(crm);

    // Limpa o campo após a exclusão
    CRMExcluir.setText("");
        
    }//GEN-LAST:event_excluirMedicoActionPerformed

    private void jButtonBuscarConsultaParaExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarConsultaParaExameActionPerformed
        // TODO add your handling code here:
        
    String cpfPaciente = jTextFieldCPFExame.getText();

    
    if (cpfPaciente.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, insira o CPF do paciente!", "Atenção", JOptionPane.WARNING_MESSAGE);
        return;
    }

    ConsultaDAO consultaDAO = new ConsultaDAO();
    consultaDAO.buscarConsultasPorPaciente(cpfPaciente);

   
    


    }//GEN-LAST:event_jButtonBuscarConsultaParaExameActionPerformed

    private void marcarExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcarExameActionPerformed
        // TODO add your handling code here:
    String descricao = DescricaoExame.getText();
    String dataExame = campoAnoExame.getText()+"-"+campoMesExame.getText()+"-"+campoDiaExame.getText();
    String horaExame = campoHoraExame.getText()+":"+campoMinutoExame.getText();
    
    int idConsulta;

    try {
        idConsulta = Integer.parseInt(jTextFieldIDConsultaExame.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "ID da consulta inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

 
    Exame exame = new Exame(descricao, dataExame, horaExame, idConsulta);

    
    ExameDAO exameDAO = new ExameDAO();
    exameDAO.salvarExame(exame);

    
    DescricaoExame.setText("");
    campoDiaExame.setText("");
    campoMesExame.setText("");
    campoAnoExame.setText("");
    campoHoraExame.setText("");
    campoMinutoExame.setText("");
    //campoResultadoExame.setText("");
    jTextFieldIDConsultaExame.setText("");
    }//GEN-LAST:event_marcarExameActionPerformed

    private void jButtonBuscarExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarExameActionPerformed
        // TODO add your handling code here:
        String cpfPaciente = jTextFieldCPFCancelarExame.getText().trim();

    if (cpfPaciente.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, insira um CPF para buscar os exames.", "Atenção", JOptionPane.WARNING_MESSAGE);
        return;
    }
    ExameDAO exameDAO = new ExameDAO();

    exameDAO.buscarExamesPorPaciente(cpfPaciente);
    }//GEN-LAST:event_jButtonBuscarExameActionPerformed

    private void cancelarExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarExameActionPerformed
        // TODO add your handling code here:
    try {
        String idExameStr = IdExameCancelar.getText().trim();

        if (idExameStr.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, insira o ID do exame para cancelar.", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idExame = Integer.parseInt(idExameStr);
        
        ExameDAO exameDAO = new ExameDAO();

        exameDAO.cancelarExame(idExame);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "O ID do exame deve ser um número válido.", "Erro", JOptionPane.ERROR_MESSAGE);
    }
      
    }//GEN-LAST:event_cancelarExameActionPerformed

    private void jButtonBuscarPorPacienteEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPorPacienteEActionPerformed
        // TODO add your handling code here:
       String cpfPaciente = jTextFieldCPFRelatoriosE.getText().trim();

    if (cpfPaciente.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, insira um CPF para buscar os exames.", "Atenção", JOptionPane.WARNING_MESSAGE);
        return;
    }
    ExameDAO exameDAO = new ExameDAO();

    exameDAO.buscarExamesPorPaciente(cpfPaciente);
        
    }//GEN-LAST:event_jButtonBuscarPorPacienteEActionPerformed

    private void jButtonBuscarPorPacienteCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPorPacienteCActionPerformed
        // TODO add your handling code here:
        String cpfPaciente = jTextFieldCPFRelatoriosC.getText();

    
    if (cpfPaciente.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, insira o CPF do paciente!", "Atenção", JOptionPane.WARNING_MESSAGE);
        return;
    }

    ConsultaDAO consultaDAO = new ConsultaDAO();
    consultaDAO.buscarConsultasPorPaciente(cpfPaciente);

   
    jTextFieldCPFRelatoriosC.setText("");
    }//GEN-LAST:event_jButtonBuscarPorPacienteCActionPerformed

    private void jButtonBuscarPorMedicoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPorMedicoCActionPerformed
        // TODO add your handling code here:
        String crm_medico = ((Medico)jComboBoxRelatorioMedicoConsulta.getSelectedItem()).getCrm();

    if (crm_medico.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, insira o CRM do médico!", "Atenção", JOptionPane.WARNING_MESSAGE);
        return;
    }

    ConsultaDAO consultaDAO = new ConsultaDAO();
    consultaDAO.relatorioConsultasPorMedico(crm_medico);

    
    
    }//GEN-LAST:event_jButtonBuscarPorMedicoCActionPerformed

    private void jButtonBuscarPorDiaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPorDiaCActionPerformed
        // TODO add your handling code here:
        String dataConsulta = jTextFieldRelatorioCampoAnoConsulta.getText()+"-"+jTextFieldRelatorioCampoMesConsulta.getText()+"-"+jTextFieldRelatorioCampoDiaConsulta.getText();

    if (dataConsulta.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, insira a data da consulta!", "Atenção", JOptionPane.WARNING_MESSAGE);
        return;
    }

    ConsultaDAO consultaDAO = new ConsultaDAO();
    consultaDAO.relatorioConsultasPorDia(dataConsulta);

    
    jTextFieldRelatorioCampoAnoConsulta.setText("");
    jTextFieldRelatorioCampoMesConsulta.setText("");
    jTextFieldRelatorioCampoDiaConsulta.setText("");
    }//GEN-LAST:event_jButtonBuscarPorDiaCActionPerformed

    private void jButtonBuscarPorMedicoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPorMedicoEActionPerformed
        // TODO add your handling code here:
    String crm_medico = ((Medico)jComboBoxRelatorioMedicoExame.getSelectedItem()).getCrm();

    if (crm_medico.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, insira o CRM do médico!", "Atenção", JOptionPane.WARNING_MESSAGE);
        return;
    }

    ExameDAO exameDAO = new ExameDAO();
    exameDAO.relatorioExamesPorMedico(crm_medico);

    
 
        
    }//GEN-LAST:event_jButtonBuscarPorMedicoEActionPerformed

    private void jButtonBuscarPorDiaEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPorDiaEActionPerformed
        // TODO add your handling code here:
    String dataExame = jTextFieldRelatorioCampoAnoExame.getText()+"-"+jTextFieldRelatorioCampoMesExame.getText()+"-"+jTextFieldRelatorioCampoDiaExame.getText();

    if (dataExame.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, insira a data do exame!", "Atenção", JOptionPane.WARNING_MESSAGE);
        return;
    }

    ExameDAO exameDAO = new ExameDAO();
    exameDAO.relatorioExamesPorDia(dataExame);

    
    jTextFieldRelatorioCampoAnoExame.setText("");
    jTextFieldRelatorioCampoMesExame.setText("");
    jTextFieldRelatorioCampoDiaExame.setText("");
    }//GEN-LAST:event_jButtonBuscarPorDiaEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaMedica dialog = new TelaMedica(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCadastrarMedico;
    private javax.swing.JTextField CRMExcluir;
    private javax.swing.JTextArea DescricaoExame;
    private javax.swing.JPanel FUNDOTELAS;
    private javax.swing.JTextField IdExameCancelar;
    private javax.swing.JPanel JPanel1;
    private javax.swing.JPanel TELAFUNDO;
    private javax.swing.JTextField TelefoneMedicoCadastrar;
    private javax.swing.JButton botaogerenciarexames;
    private javax.swing.JButton botaogerenciarexames1;
    private javax.swing.JButton botaorelatorios;
    private javax.swing.JTextField campoAnoExame;
    private javax.swing.JTextField campoDiaExame;
    private javax.swing.JTextField campoHoraExame;
    private javax.swing.JTextField campoMesExame;
    private javax.swing.JTextField campoMinutoExame;
    private javax.swing.JButton cancelarExame;
    private javax.swing.JTextField emailMedicoCadastrar;
    private javax.swing.JTextArea especialidadeMedico;
    private javax.swing.JButton excluirMedico;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBuscarConsultaParaExame;
    private javax.swing.JButton jButtonBuscarExame;
    private javax.swing.JButton jButtonBuscarPorDiaC;
    private javax.swing.JButton jButtonBuscarPorDiaE;
    private javax.swing.JButton jButtonBuscarPorMedicoC;
    private javax.swing.JButton jButtonBuscarPorMedicoE;
    private javax.swing.JButton jButtonBuscarPorPacienteC;
    private javax.swing.JButton jButtonBuscarPorPacienteE;
    private javax.swing.JComboBox<String> jComboBoxRelatorioMedicoConsulta;
    private javax.swing.JComboBox<String> jComboBoxRelatorioMedicoExame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField jTextFieldCPFCancelarExame;
    private javax.swing.JTextField jTextFieldCPFExame;
    private javax.swing.JTextField jTextFieldCPFRelatoriosC;
    private javax.swing.JTextField jTextFieldCPFRelatoriosE;
    private javax.swing.JTextField jTextFieldCRMCadastrar;
    private javax.swing.JTextField jTextFieldIDConsultaExame;
    private javax.swing.JTextField jTextFieldNomeMedicoCadastrar;
    private javax.swing.JTextField jTextFieldRelatorioCampoAnoConsulta;
    private javax.swing.JTextField jTextFieldRelatorioCampoAnoExame;
    private javax.swing.JTextField jTextFieldRelatorioCampoDiaConsulta;
    private javax.swing.JTextField jTextFieldRelatorioCampoDiaExame;
    private javax.swing.JTextField jTextFieldRelatorioCampoMesConsulta;
    private javax.swing.JTextField jTextFieldRelatorioCampoMesExame;
    private javax.swing.JButton marcarExame;
    private javax.swing.JPanel telagerenciarexames;
    private javax.swing.JPanel telagerenciarmedicos;
    private javax.swing.JPanel telarelatorios;
    // End of variables declaration//GEN-END:variables
}
